networks:
  local_docker:
    external: true

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure:5
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4', # set UTF-8 encoding
        '--collation-server=utf8mb4_unicode_ci', # set collation for Unicode compatibility
        '--default-authentication-plugin=mysql_native_password', # ensures compatibility with older MySQL clients
        '--log-error=/var/lib/mysql/mysql-error.log' # sets the location for error logs
      ]
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER:-root} # if not provided, use root as default value
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - local_docker

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - local_docker